fileFormats = {
    "Web": [".html5", ".html", ".htm", ".xhtml"],
    "Picture": [
        ".jpeg",
        ".jpg",
        ".tiff",
        ".gif",
        ".bmp",
        ".png",
        ".bpg",
        "svg",
        ".heif",
        ".psd",
    ],
    "Video": [
        ".avi",
        ".mkv",
        ".flv",
        ".wmv",
        ".mov",
        ".mp4",
        ".webm",
        ".vob",
        ".mng",
        ".qt",
        ".mpg",
        ".mpeg",
        ".3gp",
    ],
    "Document": [
        ".oxps",
        ".pages",
        ".docx",
        ".txt",
        ".doc",
        ".fdf",
        ".ods",
        ".odt",
        ".pwi",
        ".xsn",
        ".xps",
        ".dotx",
        ".docm",
        ".dox",
        ".rvg",
        ".rtf",
        ".rtfd",
        ".wpd",
        ".xls",
        ".xlsx",
        ".ppt",
        "pptx",
    ],
    "Compressed": [
        ".a",
        ".ar",
        ".cpio",
        ".tar",
        ".gz",
        ".rz",
        ".7z",
        ".dmg",
        ".rar",
        ".xar",
        ".zip",
    ],
    "Audio": [
        ".aac",
        ".aa",
        ".aac",
        ".dvf",
        ".m4a",
        ".m4b",
        ".m4p",
        ".mp3",
        ".msv",
        "ogg",
        "oga",
        ".raw",
        ".vox",
        ".wav",
        ".wma",
    ],
    "Executable": [
        ".exe", 
        ".msi",
        ],
    "Images Iso": [".iso"],
    "Pdfs": [
        ".pdf",
        ".epub",
    ],
}